name: Deploy docs to github pages
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install deps
        run: |
          pip3 install -e .[doc,test]
      - name: Run sphinx autodoc
        run: |
          sphinx-apidoc  -o doc nap
      - name: Build docs
        run: |
          make -C doc html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./doc/_build
