name: Python package

on: [push]

jobs:
  install_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d --sequential --skip-lock
    - name: Test
      uses: VaultVulp/action-pipenv@v2.0.1
      env:
        NMIGEN_USE_YOSYS: system
        YOSYS: yowasp-yosys
      with:
        command: run test