name: Vivado Builds

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build_applet:
    strategy:
      fail-fast: false
      matrix:
        applet:
        - applets/camera.py -b -d MicroR2 -s Zynq
        - applets/hdmi_framebuffer.py -b -d MicroR2 -s Zynq
        - applets/hdmi_framebuffer.py -b -d Beta -s Zynq
        - applets/hdmi_framebuffer.py -b -d Zybo -s Zynq
    runs-on: vivado
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: '3.10'
    - uses: YosysHQ/setup-oss-cad-suite@v3
    - name: Install dependencies
      run: pdm install -G test
    - name: Run test suite
      run:
        pdm run ${{ matrix.applet }}
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: build_hdmi_test_${{ matrix.device }}_${{ matrix.soc_platform }}
        path: build/*/*
