name: python testsuite and deploy
on: [push]
jobs:
  run_testsuite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install fpga-tools
        run: |
          curl -s https://api.github.com/repos/yosysHQ/fpga-toolchain/releases/latest | grep "browser_download_url.*xz" | cut -d : -f 2,3 | tr -d "\"" | wget -qi - -O fpga_toolchain.tar.xz
          tar -C / -xf fpga_toolchain.tar.xz fpga-toolchain/
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          pip3 install -e .[doc,test]
      - name: Run test suite
        run:
          pytest

  publish_pypi:
    if: ${{ github.ref == 'main' }}
    needs: run_testsuite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          pip3 install twine setuptools-scm
      - name: Build package
        run: |
          ./setup.py build sdist
      - name: Upload to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: 1
        run: |
          twine upload dist/naps*

  publish_docs:
    if: ${{ github.ref == 'main' }}
    needs: run_testsuite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          pip3 install -e .[doc,test]
      - name: Run sphinx autodoc
        run: |
          sphinx-apidoc  -o doc naps
      - name: Build docs
        run: |
          make -C doc html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./doc/_build/html